language: python
python:
    - "3.4"
before_install:
    - "which python"
    - "deactivate"
    - "which python"
    - "which python2.6"
    - "which python2.7"
    - "which python3"
    - "which python3.2"
    - "which python3.3"
    - "which python3.4"
    - "ls -al /opt/python/3.4.0/bin"
    - "ls -al /opt/python/pypy-2.2.1/bin"
    - "easy_install --version"
    - "pip freeze"
    - "travis_retry pip install -U setuptools"
    - "pwd"
    - "ls -alrt /opt/python"
    - "ls -alrt /opt/pyenv"
    - "cd `mktemp -d`"
    - "pwd"
    - "travis_retry wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py"
    - "python get-pip.py"
    - "cd $OLDPWD"
    - "pwd"
    - "pip --version"
    - "easy_install --version"
install:
#    - "pip install http://msmhrt.jp/dummy_url_for_timeout.tar.gz"
#    - "travis_retry pip install -r requirements.txt -r test-requirements.txt"
    - "travis_retry pip install -r test-requirements.txt"
before_script:
    - "pip freeze -r test-requirements.txt"
    - "set"
    - "ls -al $HOME"
    - "ls -al /home/travis/virtualenv/python2.6/bin"
    - "ls -al /usr/local/pypy/bin"
    - "ls -al /usr/local/gradle/bin"
    - "ls -al /usr/local/sbin"
    - "ls -al /usr/local/bin"
    - "ls -al /usr/sbin"
    - "ls -al /usr/bin"
    - "ls -al /sbin"
    - "ls -al /bin"
    - "cat ~/.profile"
    - "cat ~/.bashrc"
    - "cat ~/.travis_ci_environment.yml"
script: "python -m  unittest"
