language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install: "pip install -r test-requirements.txt"
install1: "pip freeze -r test-requirements.txt"
install2: "pip freeze -l -r test-requirements.txt"
install3: "pip freeze -r -r test-requirements.txt"
install4: "set"
install5: "ls -al"
#before_script: "ls -al .pip"
before_install: "/bin/sh travis.sh"
after_install: "/bin/sh travis.sh"
script: "python -m  unittest"
