language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
before_install: "echo before_install"
install: "pip install -r test-requirements.txt"
after_install: "echo after_install"
before_script: "/bin/sh travis.sh"
script: "python -m  unittest"
after_script: "echo after_script"
