language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install: "pip install -r test-requirements.txt"
install: "pip freeze -r test-requirements.txt"
install: "pip freeze -l -r test-requirements.txt"
install: "pip freeze -r -r test-requirements.txt"
install: "set"
install: "ls -al"
#before_script: "ls -al .pip"
before_install: "ls -al"
script: "python -m  unittest"
